### PR TITLE
Image Captioning

### PR DESCRIPTION
**Pull request by NishantPrabhu**
Added image captioning tutorial.

### CODE REVIEW

**Comment by MukundVarmaT** [comment]
@NishantPrabhu  there is a missing picture `Caption input format`. Just confirming a look ahead mask is used in to create the context vector right? Also the starting token there is?

**Comment by NishantPrabhu** [comment]
Look ahead mask should not be needed because captions only up to the current timestep are provided while training. I'll check out the missing image issue and fix it.

**Comment by MukundVarmaT** [comment]
okay so for the first word what is it? `<start> token`?

**Comment by NishantPrabhu** [comment]
Yeah, startseq for the first word.

**Comment by NishantPrabhu** [comment]
You should see the missing image now.

**Pull request merged**
